"""
pipeline/state.py

Defines PipelineState — the single data structure passed between all agents
in the research pipeline. Fields are populated exactly once by the agent
responsible for each section. No agent modifies another agent's fields.

Design notes:
  - user_query and criteria are set at planning time in main.py and are
    immutable for the entire execution. Agents may read them but must never
    overwrite them.
  - claims and the provenance log are conceptually distinct even though they
    carry similar information. claims is the Researcher's raw extraction output
    stored on state for downstream agents to read. The provenance log is the
    separate audit structure that enables the Verifier's concentration check.
  - concentration_flag is stubbed False by default. The Verifier will set it
    to True if the source concentration check fires.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class PipelineState:
    # ------------------------------------------------------------------ #
    # Planning-time fields — set in main.py, never modified by any agent  #
    # ------------------------------------------------------------------ #

    user_query: str
    """The original user query. Fixed at planning time."""

    criteria: list[str]
    """
    Criteria extracted from the user query at planning time.
    Each string is one criterion the user cares about
    (e.g. 'proximity to BTS Skytrain', 'breakfast included').
    """

    # ------------------------------------------------------------------ #
    # Researcher fields — populated by researcher.py                      #
    # ------------------------------------------------------------------ #

    sub_queries: list[str] = field(default_factory=list)
    """
    Search sub-queries generated by the Researcher from user_query.
    Stored for debugging and evaluation tracing. Not used by downstream agents.
    """

    retrieved_pages: dict = field(default_factory=dict)
    """
    Maps URL (or local file path) -> full plain-text content of that page.
    Populated by LocalHTMLFetcher via the Researcher. Downstream agents
    should not fetch content directly — read from this dict instead.
    """

    claims: list[dict] = field(default_factory=list)
    """
    Structured claims extracted from retrieved pages by the Researcher.
    Each dict has exactly these keys:
        text        (str)  — the factual claim as a sentence
        hotel       (str)  — which hotel the claim is about
        criterion   (str)  — which criterion from `criteria` it supports
        source_url  (str)  — the URL/path the claim was extracted from

    This is the Researcher's raw output. It feeds into the provenance log
    in provenance.py, but is kept separate so agents can read it directly
    without querying the log.
    """

    # ------------------------------------------------------------------ #
    # Analyzer fields — populated by analyzer.py                          #
    # ------------------------------------------------------------------ #

    rankings: list[str] = field(default_factory=list)
    """
    Hotel names in ranked order, best first. Populated by the Analyzer
    based on the claims in state. Must not be modified by any other agent.
    """

    reasoning: str = ""
    """
    The Analyzer's natural-language explanation of its ranking decision.
    Stored for the final report and for debugging.
    """

    # ------------------------------------------------------------------ #
    # Verifier fields — populated by verifier.py                          #
    # ------------------------------------------------------------------ #

    concentration_flag: bool = False
    """
    Set to True by the Verifier if the top-ranked hotel's supporting
    evidence derives disproportionately from a single source URL.
    Stubbed False for the baseline phase. The full check is implemented
    in the provenance + concentration phase.
    """

    # ------------------------------------------------------------------ #
    # RecommendationAgent fields — populated by recommendation.py         #
    # ------------------------------------------------------------------ #

    final_report: Optional[str] = None
    """
    The final human-readable recommendation report produced by the
    RecommendationAgent. None until that agent runs.
    """