"""
pipeline/state.py

Defines PipelineState — the single data structure passed between all agents
in the research pipeline. Fields are populated exactly once by the agent
responsible for each section. No agent modifies another agent's fields.

Design notes:
  - user_query is set at invocation time and is immutable for the entire
    execution. Agents may read it but must never overwrite it.
  - claims and the provenance log are conceptually distinct even though they
    carry similar information. claims is the Researcher's raw extraction output
    stored on state for downstream agents to read. The provenance log is the
    separate audit structure that enables the Verifier's concentration check.
  - concentration_flag is False by default. The Verifier sets it to True
    if the source concentration check fires.
  - Defense fields (provenance_log, concentration_score, defense_triggered)
    are None in no_defense and controlvalve_only configurations. Only
    populated when defense_config == "full_system".
"""

from typing import Optional, Any


# LangGraph requires TypedDict for state — using that here for compatibility
# while keeping field documentation from the original dataclass design.
from typing import TypedDict, List


class PipelineState(TypedDict, total=False):

    # ------------------------------------------------------------------ #
    # Planning-time fields — set at invocation, never modified by agents  #
    # ------------------------------------------------------------------ #

    user_query: str
    """The original user query. Fixed at invocation time."""

    # ------------------------------------------------------------------ #
    # Researcher fields — populated by researcher.py                      #
    # ------------------------------------------------------------------ #

    sub_queries: List[str]
    """
    Search sub-queries generated by the Researcher from user_query.
    Stored for debugging and evaluation tracing.
    """

    retrieved_pages: List[str]
    """
    List of URLs retrieved by the Researcher, in descending similarity order.
    This ordering is the observed covariate for retrieval rank analysis.
    """

    claims: List[dict]
    """
    Structured claims extracted from retrieved pages by the Researcher.
    Each dict has exactly these keys:
        text        (str)  — the factual claim as a sentence
        hotel       (str)  — which hotel the claim is about
        criterion   (str)  — which criterion it supports
        source_url  (str)  — the URL the claim was extracted from
    """

    # ------------------------------------------------------------------ #
    # Analyzer fields — populated by analyzer.py                          #
    # ------------------------------------------------------------------ #

    rankings: List[str]
    """Hotel names in ranked order, best first."""

    reasoning: str
    """The Analyzer's natural-language explanation of its ranking decision."""

    # ------------------------------------------------------------------ #
    # Verifier fields — populated by verifier.py                          #
    # ------------------------------------------------------------------ #

    concentration_flag: bool
    """
    True if the top-ranked hotel's evidence derives disproportionately
    from a single source URL. False by default (no_defense / controlvalve_only).
    """

    provenance_log: Optional[List[dict]]
    """
    Audit log of claim-to-source mappings for the top-ranked hotel.
    Each entry: { "claim": str, "source_url": str, "criterion": str }
    None unless defense_config == "full_system".
    """

    concentration_score: Optional[float]
    """
    Fraction of top-ranked hotel's claims derived from the single most
    dominant source URL. None unless defense_config == "full_system".
    Range [0.0, 1.0]. Threshold for flagging is set in verifier.py.
    """

    concentration_flagged: Optional[bool]
    """
    True if concentration_score exceeds the detection threshold.
    Distinct from concentration_flag: this is the computed result,
    concentration_flag is the legacy boolean stub.
    None unless defense_config == "full_system".
    """

    defense_triggered: Optional[bool]
    """
    True if any defense component (provenance + concentration check)
    intervened in the pipeline output. None unless defense_config == "full_system".
    """

    # ------------------------------------------------------------------ #
    # RecommendationAgent fields — populated by recommendation.py         #
    # ------------------------------------------------------------------ #

    final_report: Optional[str]
    """
    The final human-readable recommendation report.
    None until the RecommendationAgent runs.
    """